cohort_name: UDN
read_length: 150
mean_coverage: 40
sample_table: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/udn_wgs_bams.hg38.txt
project_dir: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow
results_dir: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/results

references:
    hg38: 
        fasta: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/GRCh38_full_analysis_set_plus_decoy_hla.fa
        dict: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/GRCh38_full_analysis_set_plus_decoy_hla.dict
        mappability: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/GRCh38.k100.mappability.bed.gz
        segdup: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/GRCh38/SegmentalDuplications/GRCh38_segdups.bed.gz

STR_catalog:
  hg38: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/ExpansionHunter.TR_catalog.json

stratify_region: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/GRCh38/union/GRCh38_notinalllowmapandsegdupregions.bed.gz
ploid_priors: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/ploidy_priors.txt
threads: 16
