cohort_name: UDN_SR_SVs
read_length: 150
mean_coverage: 50
sample_table: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/sample_bams.txt
project_dir: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow
results_dir: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/results

references:
    hg38: /oak/stanford/groups/euan/projects/tannerj/short_read_SV_workflow/references/hg38.full_analysis_set.fasta

threads: 1
